### ISSUE TITLE
Plugin availability on production Croogo site

### ISSUE THREAD

**Issue by ricog** [fahad19/clear_cache#2]
I had some trouble on a production Croogo site. The plugin would activate, but the menu option wasn't visible until I manually cleared the cache the first time. I couldn't even access the route directly. I'm not exactly sure why that would happen.

If you have any insight, let me me know and I'll see if I can resolve it.

Thanks,
Rick

**Comment by fahad19** [comment]
I have experienced similar problem too. CakePHP won't know of any file changes in production mode (debug level set to 0) until the cache is cleared.

Only solution that I can think of is having some sort of additional stuff in Extensions plugin of Croogo that takes care of clearing cache once a plugin is activated/deactivated/upload.

**Comment by ricog** [comment]
This is a really old issue and not something I'm tracking any longer. For all I know it could be fixed or no longer relevant. So closing.
